# imported from $HOME/.alacritty.yml with
# import:
#   - ~/.config/dotfiles/alacritty.yml

env:
  TERM: xterm-256color
window:
  opacity: 0.95
  # padding:
  #   x: 8
  #   y: 5
  startup_mode: Fullscreen
font:
  normal:
    family: CaskaydiaCove Nerd Font Mono 
  size: 10
key_bindings:
  - { key: F11, action: ToggleFullscreen }
shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"
