# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true
format = """$all$directory$character """
right_format = '$time'

[time]
disabled = false
style = "bold bright-black"
format = "[$time]($style)"

[username]
format = '[$user]($style) '
show_always = true
style_root = 'bold red' 
style_user = 'bold 3'

[directory]
style = 'bold 12' 

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
format = '[➜](bold bright-black)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

